spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DB_URL}/${DB_NAME}?zeroDateTimeBehavior=CONVERT_TO_NULL&verifyServerCertificate=false&useSSL=true
    username: ${DB_USERNAME}
    password: ${DB_PWD}
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
  servlet:
    context-path: /easycron
